CREATE TABLE [dbo].[Group] (
    [groupID] SMALLINT      IDENTITY (1, 1) NOT NULL,
    [name]    NVARCHAR (32) NOT NULL,
    CONSTRAINT [PK_Group] PRIMARY KEY CLUSTERED ([groupID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [UIX_Group_name] UNIQUE NONCLUSTERED ([name] ASC) WITH (FILLFACTOR = 90)
);


GO
ALTER TABLE [dbo].[Group] SET (LOCK_ESCALATION = AUTO);

