//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Merlin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно активировать акцию, так как она содержит выпуски спонсорских программ без предмета рекламы. Операция прервана..
        /// </summary>
        public static string ActivationWithProgramIssuesWithoutAdvType {
            get {
                return ResourceManager.GetString("ActivationWithProgramIssuesWithoutAdvType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данной распечатке акта выполненных работ присутствуют выпуски на радиостанциях, которые не были отмечены как обработанные трафик-менеджером..
        /// </summary>
        public static string ActJournalMassmediaExplamation {
            get {
                return ResourceManager.GetString("ActJournalMassmediaExplamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для редактирования активированной спонскорской компании необходимо выбрать предмет рекламы..
        /// </summary>
        public static string AdvertTypeMastBeSelected {
            get {
                return ResourceManager.GetString("AdvertTypeMastBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать предмет рекламы..
        /// </summary>
        public static string AdvertTypeNotSelected {
            get {
                return ResourceManager.GetString("AdvertTypeNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекламное агентство успешно изменено..
        /// </summary>
        public static string AgencyChangeSuccess {
            get {
                return ResourceManager.GetString("AgencyChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выпуски рекламной кампании проэкспортированы..
        /// </summary>
        public static string CampaignExportSuccess {
            get {
                return ResourceManager.GetString("CampaignExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал переносов кампании.
        /// </summary>
        public static string CampaignIssuesTransfersTitle {
            get {
                return ResourceManager.GetString("CampaignIssuesTransfersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно прочитать файл, или формат файла не верный. Операция прервана..
        /// </summary>
        public static string CannotReadExportFile {
            get {
                return ResourceManager.GetString("CannotReadExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно прочитать импортируемый файл. Убедитесь что файл выбран правильно..
        /// </summary>
        public static string CannotReadImportFile {
            get {
                return ResourceManager.GetString("CannotReadImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно сменить агентство для выбранной рекламной кампании. Она либо завершилась, либо началась в одном из предыдущих месяцев..
        /// </summary>
        public static string ChangeAgencyIsForbidden {
            get {
                return ResourceManager.GetString("ChangeAgencyIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно сменить тип оплаты для выбранной рекламной кампании. Она либо завершилась, либо началась в одном из предыдущих месяцев..
        /// </summary>
        public static string ChangePaymentTypeIsForbidden {
            get {
                return ResourceManager.GetString("ChangePaymentTypeIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка новых сообщений в системе....
        /// </summary>
        public static string CheckNewMessage {
            get {
                return ResourceManager.GetString("CheckNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только пользователь с правами администратора может деактивировать акцию, которая уже началась!.
        /// </summary>
        public static string DeactivationNotAllowed {
            get {
                return ResourceManager.GetString("DeactivationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неактивированные акции в прошлом успешно удалены..
        /// </summary>
        public static string DeleteActionsInPastCompleted {
            get {
                return ResourceManager.GetString("DeleteActionsInPastCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы пытаетесь создать ролик-пустышку с нулевой прододжительностью. Это запрещено..
        /// </summary>
        public static string DummyRollerWithZeroDuration {
            get {
                return ResourceManager.GetString("DummyRollerWithZeroDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap erase {
            get {
                object obj = ResourceManager.GetObject("erase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap erase2 {
            get {
                object obj = ResourceManager.GetObject("erase2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СМИ данной кампании отличается от СМИ экспортируемого файла..
        /// </summary>
        public static string ExportDifferentMassmedias {
            get {
                return ResourceManager.GetString("ExportDifferentMassmedias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При экспорте произошли ошибки. Возможно, не все файлы проэкспортировались. Обратитесь к вашему системному администратору за помощью..
        /// </summary>
        public static string ExportProblem {
            get {
                return ResourceManager.GetString("ExportProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанная дирректория не существует. Убедитесь в правильности ввода и попробуйте снова..
        /// </summary>
        public static string ExportProblemDirectoryDosntExist {
            get {
                return ResourceManager.GetString("ExportProblemDirectoryDosntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблемы при экспорте.
        /// </summary>
        public static string ExportProblemTitle {
            get {
                return ResourceManager.GetString("ExportProblemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fan {
            get {
                object obj = ResourceManager.GetObject("Fan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля &apos;Оканчивая&apos; должно быть больше даты окончания действия прайс-листа: {0}..
        /// </summary>
        public static string FinishDateShouldBeInsidePricelistDates {
            get {
                return ResourceManager.GetString("FinishDateShouldBeInsidePricelistDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фирма-заказчик успешно изменена..
        /// </summary>
        public static string FirmChangeSuccess {
            get {
                return ResourceManager.GetString("FirmChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно проимпортировано фирм: {0}..
        /// </summary>
        public static string FirmImportResult {
            get {
                return ResourceManager.GetString("FirmImportResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GoLeft {
            get {
                object obj = ResourceManager.GetObject("GoLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GoRight {
            get {
                object obj = ResourceManager.GetObject("GoRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для того, чтобы назначить предмет рекламы для этого ролика, пожалуйста, используйте журнал рекламных акций..
        /// </summary>
        public static string ImpossibleSetAdvertType {
            get {
                return ResourceManager.GetString("ImpossibleSetAdvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка лицензии....
        /// </summary>
        public static string LicenseCheck {
            get {
                return ResourceManager.GetString("LicenseCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неудалось проверить лицензию или она просрочена..
        /// </summary>
        public static string LicenseError {
            get {
                return ResourceManager.GetString("LicenseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно добавить СМИ, так как будет превышено максимальное возможное количество СМИ, разрешенное по лицензии..
        /// </summary>
        public static string LicenseErrorCannotAddMassmedia {
            get {
                return ResourceManager.GetString("LicenseErrorCannotAddMassmedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при проверке лицензии.{0}Превышено максимальное число СМИ..
        /// </summary>
        public static string LicenseErrorMassmediaCount {
            get {
                return ResourceManager.GetString("LicenseErrorMassmediaCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при проверке лицензии.{0}Лицензия зарегистрированная на другой продукт..
        /// </summary>
        public static string LicenseErrorProduct {
            get {
                return ResourceManager.GetString("LicenseErrorProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно осуществить вход в систему &quot;Рекламное агенство&quot; с ролью главного администратора..
        /// </summary>
        public static string LoginErrorWithSuperAdmin {
            get {
                return ResourceManager.GetString("LoginErrorWithSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка меню приложения....
        /// </summary>
        public static string LoginLoadMenu {
            get {
                return ResourceManager.GetString("LoginLoadMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден прайс-лист для модуля &apos;{0}&apos; на указанную дату..
        /// </summary>
        public static string ModulePricelistNotFound {
            get {
                return ResourceManager.GetString("ModulePricelistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mute_roller {
            get {
                object obj = ResourceManager.GetObject("mute_roller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая цена не должна быть равна текущей цене..
        /// </summary>
        public static string NewPriceShouldBeDifferent {
            get {
                return ResourceManager.GetString("NewPriceShouldBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать хотя бы одно агентство..
        /// </summary>
        public static string NoAgencySelected {
            get {
                return ResourceManager.GetString("NoAgencySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать тип рекламной кампании..
        /// </summary>
        public static string NoCampaignTypeSelected {
            get {
                return ResourceManager.GetString("NoCampaignTypeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать дату подписания договора для всех выбранных агентств.
        /// </summary>
        public static string NoContractDateSet {
            get {
                return ResourceManager.GetString("NoContractDateSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ничего не выбрали. Пожалуйста, выберите хотя бы один рекламный выпуск. Операция прервана..
        /// </summary>
        public static string NoIssueSelected {
            get {
                return ResourceManager.GetString("NoIssueSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выбранной даты отсутствует прайс-лист..
        /// </summary>
        public static string NoPricelistForGivenDate {
            get {
                return ResourceManager.GetString("NoPricelistForGivenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать хотя бы одну радиостанцию..
        /// </summary>
        public static string NoRadiostationSelected {
            get {
                return ResourceManager.GetString("NoRadiostationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выбранной даты не сгенерированы рекламные окна..
        /// </summary>
        public static string NoTariffWindowForGivenDate {
            get {
                return ResourceManager.GetString("NoTariffWindowForGivenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open3 {
            get {
                object obj = ResourceManager.GetObject("open3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет прав на выполнение данной операции!.
        /// </summary>
        public static string OperationNotAllowed {
            get {
                return ResourceManager.GetString("OperationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден прайс-лист для пакетного модуля &apos;{0}&apos; на указанную дату..
        /// </summary>
        public static string PackModulePricelistNotFound {
            get {
                return ResourceManager.GetString("PackModulePricelistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип оплаты успешно изменён..
        /// </summary>
        public static string PaymentTypeChangeSuccess {
            get {
                return ResourceManager.GetString("PaymentTypeChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap printer1 {
            get {
                object obj = ResourceManager.GetObject("printer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден прайс-лист для программы &apos;{0}&apos; на указанную дату..
        /// </summary>
        public static string SponsorPricelistNotFound {
            get {
                return ResourceManager.GetString("SponsorPricelistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден прайс-лист для программы &apos;{0}&apos; на указанную дату..
        /// </summary>
        public static string SponsorTariffNotFound {
            get {
                return ResourceManager.GetString("SponsorTariffNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля &apos;Начиная с&apos; не должно быть меньше даты начала действия прайс-листа: {0}..
        /// </summary>
        public static string StartDateShouldBeInsidePricelistDates {
            get {
                return ResourceManager.GetString("StartDateShouldBeInsidePricelistDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы пытаетесь заменить рекламный ролик в активированной рекламной акции на ролик-пустышку без предмета рекламы. Операция прервана..
        /// </summary>
        public static string SubstitutionImpossibleForDummyRoller {
            get {
                return ResourceManager.GetString("SubstitutionImpossibleForDummyRoller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден тариф для выполнения данной операции!.
        /// </summary>
        public static string TariffNotFound {
            get {
                return ResourceManager.GetString("TariffNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите ролик для замены..
        /// </summary>
        public static string TitleGetRollerForSubstitude {
            get {
                return ResourceManager.GetString("TitleGetRollerForSubstitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ластик {
            get {
                object obj = ResourceManager.GetObject("Ластик", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ластик1 {
            get {
                object obj = ResourceManager.GetObject("Ластик1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
